package net.kaneka.planttech2.datagen.blocks;

import net.kaneka.planttech2.blocks.GrowingBlock;
import net.kaneka.planttech2.blocks.machines.EnergyStorageBlock;
import net.kaneka.planttech2.registries.ModBlocks;
import net.minecraft.block.Block;
import net.minecraft.block.HorizontalBlock;
import net.minecraft.util.Direction;
import net.minecraft.util.Direction.Axis;
import net.minecraftforge.client.model.generators.BlockModelBuilder;
import net.minecraftforge.client.model.generators.BlockStateProvider;
import net.minecraftforge.client.model.generators.ModelBuilder.FaceRotation;

public class MachineModels extends BlockModelBase
{

	MachineModels(BlockStateProvider states)
	{
		super(states);
	}

	@Override
	void registerStatesAndModels()
	{
		BlockModelBuilder three_layered_six_sided_nubs = models().withExistingParent("block/basic/three_layered_six_sided_nubs","block/block")
				 	.element().from(0.0f, 0.0f, 0.0f).to(16.0f, 16.0f, 16.0f)
				 		.face(Direction.byName("north")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#north_0").end()
				 		.face(Direction.byName("east")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#east_0").end()
				 		.face(Direction.byName("south")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#south_0").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#west_0").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#up_0").end()
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#down_0").end().end()
				 	.element().from(0.0f, 0.0f, 0.0f).to(16.0f, 16.0f, 16.0f)
				 		.face(Direction.byName("north")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#north_1").end()
				 		.face(Direction.byName("east")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#east_1").end()
				 		.face(Direction.byName("south")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#south_1").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#west_1").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#up_1").end()
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#down_1").end().end()
				 	.element().from(0.0f, 0.0f, 0.0f).to(16.0f, 16.0f, 16.0f)
				 		.face(Direction.byName("north")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#north_2").end()
				 		.face(Direction.byName("east")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#east_2").end()
				 		.face(Direction.byName("south")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#south_2").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#west_2").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#up_2").end()
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#down_2").end().end()
				 	.element().from(8.0f, 0.0f, 19.0f).to(8.0f, 16.0f, 21.0f)
				 		.rotation().angle(-45.0f).axis(Axis.byName("y")).origin(8.0f, 8.0f, 8.0f).end()
				 		.face(Direction.byName("north")).uvs(0.0f, 0.0f, 0.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("east")).uvs(2.0f, 0.0f, 4.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("south")).uvs(0.0f, 0.0f, 0.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 2.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 2.0f, 0.0f)
				 	.rotation(FaceRotation.COUNTERCLOCKWISE_90).texture("#nubs").end()
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 2.0f, 0.0f)
				 	.rotation(FaceRotation.CLOCKWISE_90)
				 	.rotation(FaceRotation.UPSIDE_DOWN)
				 	.rotation(FaceRotation.COUNTERCLOCKWISE_90).texture("#nubs").end().end()
				 	.element().from(8.0f, 0.0f, -5.0f).to(8.0f, 16.0f, -3.0f)
				 		.rotation().angle(-45.0f).axis(Axis.byName("y")).origin(8.0f, 8.0f, 8.0f).end()
				 		.face(Direction.byName("north")).uvs(0.0f, 0.0f, 0.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("east")).uvs(4.0f, 0.0f, 6.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("south")).uvs(0.0f, 0.0f, 0.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("west")).uvs(6.0f, 0.0f, 8.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 2.0f, 0.0f)
				 	.rotation(FaceRotation.COUNTERCLOCKWISE_90).texture("#nubs").end()
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 2.0f, 0.0f)
				 	.rotation(FaceRotation.CLOCKWISE_90)
				 	.rotation(FaceRotation.UPSIDE_DOWN)
				 	.rotation(FaceRotation.COUNTERCLOCKWISE_90).texture("#nubs").end().end()
				 	.element().from(19.0f, 0.0f, 8.0f).to(21.0f, 16.0f, 8.0f)
				 		.rotation().angle(-45.0f).axis(Axis.byName("y")).origin(8.0f, 8.0f, 8.0f).end()
				 		.face(Direction.byName("north")).uvs(10.0f, 0.0f, 12.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("east")).uvs(0.0f, 0.0f, 0.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("south")).uvs(8.0f, 0.0f, 10.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 0.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 0.0f, 2.0f)
				 	.rotation(FaceRotation.COUNTERCLOCKWISE_90).texture("#nubs").end()
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 0.0f, 2.0f)
				 	.rotation(FaceRotation.CLOCKWISE_90)
				 	.rotation(FaceRotation.UPSIDE_DOWN)
				 	.rotation(FaceRotation.COUNTERCLOCKWISE_90).texture("#nubs").end().end()
				 	.element().from(-5.0f, 0.0f, 8.0f).to(-3.0f, 16.0f, 8.0f)
				 		.rotation().angle(-45.0f).axis(Axis.byName("y")).origin(8.0f, 8.0f, 8.0f).end()
				 		.face(Direction.byName("north")).uvs(12.0f, 0.0f, 14.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("east")).uvs(0.0f, 0.0f, 0.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("south")).uvs(14.0f, 0.0f, 16.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 0.0f, 16.0f).texture("#nubs").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 0.0f, 2.0f)
				 	.rotation(FaceRotation.COUNTERCLOCKWISE_90).texture("#nubs").end()
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 0.0f, 2.0f)
				 	.rotation(FaceRotation.CLOCKWISE_90)
				 	.rotation(FaceRotation.UPSIDE_DOWN)
				 	.rotation(FaceRotation.COUNTERCLOCKWISE_90).texture("#nubs").end().end();
				 BlockModelBuilder three_layered_six_sided = models().withExistingParent("block/basic/three_layered_six_sided", "block/block")
				 	.element().from(0.0f, 0.0f, 0.0f).to(16.0f, 16.0f, 16.0f)
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#down_0").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#up_0").end()
				 		.face(Direction.byName("north")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#north_0").end()
				 		.face(Direction.byName("south")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#south_0").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#west_0").end()
				 		.face(Direction.byName("east")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#east_0").end().end()
				 	.element().from(0.0f, 0.0f, 0.0f).to(16.0f, 16.0f, 16.0f)
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#down_1").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#up_1").end()
				 		.face(Direction.byName("north")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#north_1").end()
				 		.face(Direction.byName("south")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#south_1").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#west_1").end()
				 		.face(Direction.byName("east")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#east_1").end().end()
				 	.element().from(0.0f, 0.0f, 0.0f).to(16.0f, 16.0f, 16.0f)
				 		.face(Direction.byName("down")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#down_2").end()
				 		.face(Direction.byName("up")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#up_2").end()
				 		.face(Direction.byName("north")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#north_2").end()
				 		.face(Direction.byName("south")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#south_2").end()
				 		.face(Direction.byName("west")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#west_2").end()
				 		.face(Direction.byName("east")).uvs(0.0f, 0.0f, 16.0f, 16.0f).texture("#east_2").end().end();
				 BlockModelBuilder chipalyzer = models().getBuilder("block/machine/chipalyzer")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/chipalyzer_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder compressor = models().getBuilder("block/machine/compressor")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/compressor_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder dna_cleaner = models().getBuilder("block/machine/dna_cleaner")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/dnacleaner_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder dna_combiner = models().getBuilder("block/machine/dna_combiner")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/dnacombiner_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder dna_extractor = models().getBuilder("block/machine/dna_extractor")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/dnaextractor_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder dna_remover = models().getBuilder("block/machine/dna_remover")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/dnaremover_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder energy_supplier = models().getBuilder("block/machine/energy_supplier")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/energy_supplier_top")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder energystorage_tier_0 = models().withExistingParent("block/machine/energystorage_tier_1", "block/orientable")
				 	.texture("top", "planttech2:blocks/machines/machines_side_top")
				 	.texture("front", "planttech2:blocks/machines/energystorage_front_tier_1")
				 	.texture("side", "planttech2:blocks/machines/machines_side_top");
				 BlockModelBuilder energystorage_tier_1 = models().withExistingParent("block/machine/energystorage_tier_2", "block/orientable")
				 	.texture("top", "planttech2:blocks/machines/machines_side_top")
				 	.texture("front", "planttech2:blocks/machines/energystorage_front_tier_2")
				 	.texture("side", "planttech2:blocks/machines/machines_side_top");
				 BlockModelBuilder energystorage_tier_2 = models().withExistingParent("block/machine/energystorage_tier_3", "block/orientable")
				 	.texture("top", "planttech2:blocks/machines/machines_side_top")
				 	.texture("front", "planttech2:blocks/machines/energystorage_front_tier_3")
				 	.texture("side", "planttech2:blocks/machines/machines_side_top");
				 BlockModelBuilder energystorage_tier_3 = models().withExistingParent("block/machine/energystorage_tier_4", "block/orientable")
				 	.texture("top", "planttech2:blocks/machines/machines_side_top")
				 	.texture("front", "planttech2:blocks/machines/energystorage_front_tier_4")
				 	.texture("side", "planttech2:blocks/machines/machines_side_top");
				 BlockModelBuilder identifier = models().getBuilder("block/machine/identifier")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/identifier_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder infuser = models().getBuilder("block/machine/infuser")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/infuser_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder machine_iron_growing_0 = models().getBuilder("block/machine/machine_iron_growing_0")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_0")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_0")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_0")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_0");
				 BlockModelBuilder machine_iron_growing_1 = models().getBuilder("block/machine/machine_iron_growing_1")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_1")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_1")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_1")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_1");
				 BlockModelBuilder machine_iron_growing_2 = models().getBuilder("block/machine/machine_iron_growing_2")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_2")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_2")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_2")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_2");
				 BlockModelBuilder machine_iron_growing_3 = models().getBuilder("block/machine/machine_iron_growing_3")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_3")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_3")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_3")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_3");
				 BlockModelBuilder machine_iron_growing_4 = models().getBuilder("block/machine/machine_iron_growing_4")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_4")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_4")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_4")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_4");
				 BlockModelBuilder machine_iron_growing_5 = models().getBuilder("block/machine/machine_iron_growing_5")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_5")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_5")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_5")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_5");
				 BlockModelBuilder machine_iron_growing_6 = models().getBuilder("block/machine/machine_iron_growing_6")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_6")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_6")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_6")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_6");
				 BlockModelBuilder machine_plantium_growing_0 = models().getBuilder("block/machine/machine_plantium_growing_0")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_0")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_0")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_0")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_0");
				 BlockModelBuilder machine_plantium_growing_1 = models().getBuilder("block/machine/machine_plantium_growing_1")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_1")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_1")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_1")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_1");
				 BlockModelBuilder machine_plantium_growing_2 = models().getBuilder("block/machine/machine_plantium_growing_2")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_2")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_2")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_2")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_2");
				 BlockModelBuilder machine_plantium_growing_3 = models().getBuilder("block/machine/machine_plantium_growing_3")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_3")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_3")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_3")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_3");
				 BlockModelBuilder machine_plantium_growing_4 = models().getBuilder("block/machine/machine_plantium_growing_4")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_4")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_4")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_4")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_4");
				 BlockModelBuilder machine_plantium_growing_5 = models().getBuilder("block/machine/machine_plantium_growing_5")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_5")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_5")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_5")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_5");
				 BlockModelBuilder machine_plantium_growing_6 = models().getBuilder("block/machine/machine_plantium_growing_6")
				 	.parent(three_layered_six_sided)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/empty")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_6")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_6")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_6")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_6");
				 BlockModelBuilder machinebulbreprocessor = models().getBuilder("block/machine/machinebulbreprocessor")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/machinebulbreprocessor_top")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder mega_furnace = models().getBuilder("block/machine/mega_furnace")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/mega_furnace_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder plantfarm = models().getBuilder("block/machine/plantfarm")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/plantfarm_top")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder planttopia_teleporter_end = models().withExistingParent("block/machine/planttopia_teleporter_end", "block/cube")
				 	.texture("particle", "planttech2:blocks/machines/machines_side_top")
				 	.texture("up", "planttech2:blocks/machines/planttopia_portal_top")
				 	.texture("down", "planttech2:blocks/machines/machines_side_top")
				 	.texture("north", "planttech2:blocks/machines/teleporter_end_side")
				 	.texture("east", "planttech2:blocks/machines/teleporter_end_side")
				 	.texture("west", "planttech2:blocks/machines/teleporter_end_side")
				 	.texture("south", "planttech2:blocks/machines/teleporter_end_side");
				 BlockModelBuilder planttopia_teleporter = models().withExistingParent("block/machine/planttopia_teleporter", "block/cube")
				 	.texture("particle", "planttech2:blocks/machines/machines_side_top")
				 	.texture("up", "planttech2:blocks/machines/planttopia_portal_top")
				 	.texture("down", "planttech2:blocks/machines/machines_side_top")
				 	.texture("north", "planttech2:blocks/machines/machines_side_top")
				 	.texture("east", "planttech2:blocks/machines/machines_side_top")
				 	.texture("west", "planttech2:blocks/machines/machines_side_top")
				 	.texture("south", "planttech2:blocks/machines/machines_side_top");
				 BlockModelBuilder seedconstructor = models().getBuilder("block/machine/seedconstructor")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/seedconstructor_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder seedsqueezer = models().getBuilder("block/machine/seedsqueezer")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "minecraft:block/iron_block")
				 	.texture("down_0", "minecraft:block/iron_block")
				 	.texture("up_0", "minecraft:block/iron_block")
				 	.texture("north_0", "minecraft:block/iron_block")
				 	.texture("south_0", "minecraft:block/iron_block")
				 	.texture("west_0", "minecraft:block/iron_block")
				 	.texture("east_0", "minecraft:block/iron_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/top_down")
				 	.texture("north_1", "planttech2:blocks/machine/seedsqueezer_front")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_front_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 BlockModelBuilder solargenerator = models().getBuilder("block/machine/solargenerator")
				 	.parent(three_layered_six_sided_nubs)
				 	.texture("particle", "planttech2:blocks/plantium_block")
				 	.texture("down_0", "planttech2:blocks/plantium_block")
				 	.texture("up_0", "planttech2:blocks/plantium_block")
				 	.texture("north_0", "planttech2:blocks/plantium_block")
				 	.texture("south_0", "planttech2:blocks/plantium_block")
				 	.texture("west_0", "planttech2:blocks/plantium_block")
				 	.texture("east_0", "planttech2:blocks/plantium_block")
				 	.texture("down_1", "planttech2:blocks/machine/top_down")
				 	.texture("up_1", "planttech2:blocks/machine/solargenerator_top")
				 	.texture("north_1", "planttech2:blocks/machine/side_6")
				 	.texture("south_1", "planttech2:blocks/machine/side_6")
				 	.texture("west_1", "planttech2:blocks/machine/side_6")
				 	.texture("east_1", "planttech2:blocks/machine/side_6")
				 	.texture("down_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("up_2", "planttech2:blocks/machine/growoverlay_top_down")
				 	.texture("north_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("south_2", "planttech2:blocks/machine/growoverlay_back_7")
				 	.texture("west_2", "planttech2:blocks/machine/growoverlay_right_7")
				 	.texture("east_2", "planttech2:blocks/machine/growoverlay_left_7")
				 	.texture("nubs", "planttech2:blocks/machine/nubs");
				 
				 
				 BlockModelBuilder[] growing_iron = new BlockModelBuilder[]{machine_iron_growing_0, 
						 													machine_iron_growing_1, 
						 													machine_iron_growing_2, 
						 													machine_iron_growing_3, 
						 													machine_iron_growing_4, 
						 													machine_iron_growing_5, 
						 													machine_iron_growing_6};
				 
				 BlockModelBuilder[] growing_plantium = new BlockModelBuilder[]{machine_plantium_growing_0, 
                                                							machine_plantium_growing_1, 
                                                							machine_plantium_growing_2, 
                                                							machine_plantium_growing_3, 
                                                							machine_plantium_growing_4, 
                                                							machine_plantium_growing_5, 
                                                							machine_plantium_growing_6};
				 
				 
                 facingBlock(ModBlocks.CHIPALYZER, chipalyzer);
                 blockItem(ModBlocks.CHIPALYZER, chipalyzer); 
                 growingMachineFacing(ModBlocks.CHIPALYZER_GROWING, growing_plantium);
                 
                 facingBlock(ModBlocks.COMPRESSOR, compressor);
                 blockItem(ModBlocks.COMPRESSOR, compressor);
                 growingMachineFacing(ModBlocks.COMPRESSOR_GROWING, growing_iron);
                 
                 facingBlock(ModBlocks.DNA_CLEANER, dna_cleaner);
                 blockItem(ModBlocks.DNA_CLEANER, dna_cleaner);
                 growingMachineFacing(ModBlocks.DNA_CLEANER_GROWING, growing_plantium);
                 
                 facingBlock(ModBlocks.DNA_COMBINER, dna_combiner);
                 blockItem(ModBlocks.DNA_COMBINER, dna_combiner);
                 growingMachineFacing(ModBlocks.DNA_COMBINER_GROWING, growing_plantium);
                 
                 facingBlock(ModBlocks.DNA_EXTRACTOR, dna_extractor);
                 blockItem(ModBlocks.DNA_EXTRACTOR, dna_extractor);
                 growingMachineFacing(ModBlocks.DNA_EXTRACTOR_GROWING, growing_plantium);
                 
                 facingBlock(ModBlocks.DNA_REMOVER, dna_remover);
                 blockItem(ModBlocks.DNA_REMOVER, dna_remover);
                 growingMachineFacing(ModBlocks.DNA_REMOVER_GROWING, growing_plantium);
                 
                 simpleBlock(ModBlocks.ENERGY_SUPPLIER, energy_supplier);
                 blockItem(ModBlocks.ENERGY_SUPPLIER, energy_supplier);
                 growingMachine(ModBlocks.ENERGY_SUPPLIER_GROWING, growing_iron);
                 
                
            	 states.getVariantBuilder(ModBlocks.ENERGYSTORAGE)
         			.partialState().with(HorizontalBlock.FACING, Direction.EAST).with(EnergyStorageBlock.TIER, 0).modelForState().modelFile(energystorage_tier_0).rotationY(90).addModel()
         			.partialState().with(HorizontalBlock.FACING, Direction.NORTH).with(EnergyStorageBlock.TIER, 0).modelForState().modelFile(energystorage_tier_0).addModel()
         			.partialState().with(HorizontalBlock.FACING, Direction.SOUTH).with(EnergyStorageBlock.TIER, 0).modelForState().modelFile(energystorage_tier_0).rotationY(180).addModel()
         			.partialState().with(HorizontalBlock.FACING, Direction.WEST).with(EnergyStorageBlock.TIER, 0).modelForState().modelFile(energystorage_tier_0).rotationY(270).addModel()
         			.partialState().with(HorizontalBlock.FACING, Direction.EAST).with(EnergyStorageBlock.TIER, 1).modelForState().modelFile(energystorage_tier_1).rotationY(90).addModel()
         			.partialState().with(HorizontalBlock.FACING, Direction.NORTH).with(EnergyStorageBlock.TIER, 1).modelForState().modelFile(energystorage_tier_1).addModel()
         			.partialState().with(HorizontalBlock.FACING, Direction.SOUTH).with(EnergyStorageBlock.TIER, 1).modelForState().modelFile(energystorage_tier_1).rotationY(180).addModel()
         			.partialState().with(HorizontalBlock.FACING, Direction.WEST).with(EnergyStorageBlock.TIER, 1).modelForState().modelFile(energystorage_tier_1).rotationY(270).addModel()
                	.partialState().with(HorizontalBlock.FACING, Direction.EAST).with(EnergyStorageBlock.TIER, 2).modelForState().modelFile(energystorage_tier_2).rotationY(90).addModel()
          			.partialState().with(HorizontalBlock.FACING, Direction.NORTH).with(EnergyStorageBlock.TIER, 2).modelForState().modelFile(energystorage_tier_2).addModel()
          			.partialState().with(HorizontalBlock.FACING, Direction.SOUTH).with(EnergyStorageBlock.TIER, 2).modelForState().modelFile(energystorage_tier_2).rotationY(180).addModel()
          			.partialState().with(HorizontalBlock.FACING, Direction.WEST).with(EnergyStorageBlock.TIER, 2).modelForState().modelFile(energystorage_tier_2).rotationY(270).addModel()
                	.partialState().with(HorizontalBlock.FACING, Direction.EAST).with(EnergyStorageBlock.TIER, 3).modelForState().modelFile(energystorage_tier_3).rotationY(90).addModel()
          			.partialState().with(HorizontalBlock.FACING, Direction.NORTH).with(EnergyStorageBlock.TIER, 3).modelForState().modelFile(energystorage_tier_3).addModel()
          			.partialState().with(HorizontalBlock.FACING, Direction.SOUTH).with(EnergyStorageBlock.TIER, 3).modelForState().modelFile(energystorage_tier_3).rotationY(180).addModel()
          			.partialState().with(HorizontalBlock.FACING, Direction.WEST).with(EnergyStorageBlock.TIER, 3).modelForState().modelFile(energystorage_tier_3).rotationY(270).addModel();;
         		
                 
                 facingBlock(ModBlocks.IDENTIFIER, identifier);
                 blockItem(ModBlocks.IDENTIFIER, identifier);
                 growingMachineFacing(ModBlocks.IDENTIFIER_GROWING, growing_iron);
                 
                 facingBlock(ModBlocks.INFUSER, infuser);
                 blockItem(ModBlocks.INFUSER, infuser);
                 growingMachineFacing(ModBlocks.INFUSER_GROWING, growing_iron);
                 
                 simpleBlock(ModBlocks.MACHINEBULBREPROCESSOR, machinebulbreprocessor);
                 blockItem(ModBlocks.MACHINEBULBREPROCESSOR, machinebulbreprocessor);
                 growingMachine(ModBlocks.MACHINEBULBREPROCESSOR_GROWING, growing_iron);
                 
                 facingBlock(ModBlocks.MEGAFURNACE, mega_furnace);
                 blockItem(ModBlocks.MEGAFURNACE, mega_furnace);
                 growingMachineFacing(ModBlocks.MEGAFURNACE_GROWING, growing_plantium);
                 
                 simpleBlock(ModBlocks.PLANTFARM, plantfarm);
                 blockItem(ModBlocks.PLANTFARM, plantfarm);
                 growingMachine(ModBlocks.PLANTFARM_GROWING, growing_plantium);
                 
                 simpleBlock(ModBlocks.PLANTTOPIA_TELEPORTER_END, planttopia_teleporter_end);
                 blockItem(ModBlocks.PLANTTOPIA_TELEPORTER_END, planttopia_teleporter_end);
                 simpleBlock(ModBlocks.PLANTTOPIA_TELEPORTER, planttopia_teleporter);
                 
                 facingBlock(ModBlocks.SEEDCONSTRUCTOR, seedconstructor);
                 blockItem(ModBlocks.SEEDCONSTRUCTOR, seedconstructor);
                 growingMachineFacing(ModBlocks.SEEDCONSTRUCTOR_GROWING, growing_plantium);
                 
                 facingBlock(ModBlocks.SEEDSQUEEZER, seedsqueezer);
                 blockItem(ModBlocks.SEEDSQUEEZER, seedsqueezer);
                 growingMachineFacing(ModBlocks.SEEDSQUEEZER_GROWING, growing_iron);
                 
                 simpleBlock(ModBlocks.SOLARGENERATOR, solargenerator);
                 blockItem(ModBlocks.SOLARGENERATOR, solargenerator);
                 growingMachine(ModBlocks.SOLARGENERATOR_GROWING, growing_plantium);
                 
                 
				 

	}
	
	protected void growingMachineFacing(Block b, BlockModelBuilder[] model)
	{
		for(int i = 0; i < 7; i++)
		{
    		states.getVariantBuilder(b)
    			.partialState().with(HorizontalBlock.FACING, Direction.EAST).with(GrowingBlock.GROWINGSTATE, i).modelForState().modelFile(model[i]).addModel()
    			.partialState().with(HorizontalBlock.FACING, Direction.NORTH).with(GrowingBlock.GROWINGSTATE, i).modelForState().modelFile(model[i]).addModel()
    			.partialState().with(HorizontalBlock.FACING, Direction.SOUTH).with(GrowingBlock.GROWINGSTATE, i).modelForState().modelFile(model[i]).addModel()
    			.partialState().with(HorizontalBlock.FACING, Direction.WEST).with(GrowingBlock.GROWINGSTATE, i).modelForState().modelFile(model[i]).addModel();
		}
	}
	
	protected void growingMachine(Block b, BlockModelBuilder[] model)
	{
		for(int i = 0; i < 7; i++)
		{
			states.getVariantBuilder(b).partialState().with(GrowingBlock.GROWINGSTATE, i).modelForState().modelFile(model[i]).addModel();
		}
	}

}
