modLoader="javafml" #mandatory
loaderVersion="[28,)" 
issueTrackerURL="https://bitbucket.org/kaneka/planttech2/issues?status=new&status=open" #optional
logoFile="examplemod.png" 
credits="Artists: veyezx, BeerCav, DinoSoup, MoonlitLamps and andrew0030"
authors="Kaneka, Setrion, poopoodice" 
[[mods]] #mandatory
modId="planttech2"
version="0.02.12"
displayName="PlantTech 2"
updateJSONURL="https://bitbucket.org/kaneka/planttech2/raw/1.15.x/update.json" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
PlantTech 2 combines plants and tech for a whole new experience
'''