modLoader="javafml" #mandatory
loaderVersion="[33,)"
license="MIT License"
issueTrackerURL="https://bitbucket.org/kaneka/planttech2/issues?status=new&status=open"
#logoFile="examplemod.png"


[[mods]] #mandatory
modId="planttech2"
version="0.02.16"
displayName="PlantTech 2"
credits="Artists: veyezx, BeerCav, DinoSoup, MoonlitLamps and andrew0030"
authors="Kaneka, Setrion, poopoodice"
updateJSONURL="https://bitbucket.org/kaneka/planttech2/raw/1.16.x/update.json"
description='''
PlantTech 2 combines plants and tech for a whole new experience
'''

[[dependencies.basedefense]]
modId="forge"
mandatory=true
versionRange="[33.0.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.basedefense]]
modId="minecraft"
mandatory=true
versionRange="[1.16.2]"
ordering="NONE"
side="BOTH"
